version: '3'
services:
  db:
    image: 'postgres:14.1'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    environment:
      - BUS_URL=amqp://user:pass@localhost:5672
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5672:5672'
  redis:
    image: 'redis:6.2.6'

    ports:
      - '6379:6379'
